services:
  - type: web
    name: light-monitor
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: light-monitor-db
          property: connectionString

databases:
  - name: light-monitor-db
    databaseName: light_monitor
    user: light_monitor_user
    plan: free
